<?php

return [
    'shakyamuni' => [
        'slug' => 'shakyamuni',
        'route_prefix' => 'shakyamuni',
        'title' => 'Namo Buddhaya!',
        'subtitle' => 'Homage to Our Compassionate Teacher, Śākyamuni!',
        'meta_description' => 'Offer before Śākyamuni Buddha at an online Buddhist altar. Light lamps, offer incense, water, flowers, and music while reciting homage and the mantra of the Glorious Conqueror.',
        'page_title' => 'Śākyamuni Shrine — Buddhist Altar',
        'seo_title' => 'Śākyamuni Online Shrine — Buddhist Altar',
        'deity_image' => 'images/shakyamuni.png',
        'deity_image_class' => 'deity-image deity-image--shakyamuni',
        'deity_alt' => 'Śākyamuni Buddha, the Glorious Conqueror',
        'body_class' => 'shrine-bg',
        'show_sky_clouds' => true,
        'prayer_partial' => 'partials.shakyamuni-prayer',
        'prayer_modal_title' => 'Homage to Śākyamuni Buddha',
        'read_prayer_label' => 'Read the Prayer',
    ],

    'avalokiteshvara' => [
        'slug' => 'avalokiteshvara',
        'route_prefix' => 'avalokiteshvara',
        'title' => 'Namo Avalokiteshvaraya!',
        'subtitle' => 'Homage to The One Who Looks Upon Beings with Compassion!',
        'meta_description' => 'Light butter lamps, offer incense, water, flowers, and music at an online shrine to Avalokiteśvara. Recite the dhāraṇī, pool mantra repetitions, and dedicate merit with practitioners worldwide.',
        'page_title' => 'Avalokiteśvara Shrine — Buddhist Altar',
        'seo_title' => 'Avalokiteśvara Online Shrine — Buddhist Altar',
        'deity_image' => 'images/avalokiteshvara.webp',
        'deity_image_class' => 'deity-image deity-image--avalokiteshvara',
        'deity_alt' => 'Avalokiteshvara, homage to the one who looks upon beings with compassion',
        'body_class' => 'shrine-bg',
        'show_sky_clouds' => true,
        'prayer_partial' => 'partials.dharani-sutra',
        'prayer_modal_title' => 'The Dhāraṇī of Noble Avalokiteśvara',
        'read_prayer_label' => 'Read the Sutra',
    ],

    'vajrasattva' => [
        'slug' => 'vajrasattva',
        'route_prefix' => 'vajrasattva',
        'title' => 'Namo Vajrasattva!',
        'subtitle' => 'Homage to Glorious Vajrasattva!',
        'meta_description' => 'Offer before Vajrasattva at an online Buddhist altar. Light lamps, offer incense, water, flowers, and music while reciting Patrul Rinpoche’s praise to the lord of purification.',
        'page_title' => 'Vajrasattva Shrine — Buddhist Altar',
        'seo_title' => 'Vajrasattva Online Shrine — Buddhist Altar',
        'deity_image' => 'images/vajrasattva.png',
        'deity_image_class' => 'deity-image deity-image--vajrasattva',
        'deity_alt' => 'Vajrasattva, the glorious lord of purification',
        'body_class' => 'shrine-bg',
        'show_sky_clouds' => true,
        'prayer_partial' => 'partials.vajrasattva-prayer',
        'prayer_modal_title' => 'In Praise of Glorious Vajrasattva',
        'read_prayer_label' => 'Read the Prayer',
    ],

    'amitayus' => [
        'slug' => 'amitayus',
        'route_prefix' => 'amitayus',
        'title' => 'Namo Amitayus!',
        'subtitle' => 'Homage to the Buddha of Infinite Life!',
        'meta_description' => 'Offer before Amitāyus at an online Buddhist altar. Light lamps, offer incense, water, flowers, and music while reciting the prayer to the Buddha of Infinite Life.',
        'page_title' => 'Amitāyus Shrine — Buddhist Altar',
        'seo_title' => 'Amitāyus Online Shrine — Buddhist Altar',
        'deity_image' => 'images/amitayus.webp',
        'deity_image_class' => 'deity-image deity-image--amitayus',
        'deity_alt' => 'Amitāyus, the Buddha of Infinite Life',
        'body_class' => 'shrine-bg',
        'show_sky_clouds' => true,
        'prayer_partial' => 'partials.amitayus-prayer',
        'prayer_modal_title' => 'A Prayer to Amitāyus',
        'read_prayer_label' => 'Read the Prayer',
    ],

    'amitabha' => [
        'slug' => 'amitabha',
        'route_prefix' => 'amitabha',
        'title' => 'Namo Amitabha!',
        'subtitle' => 'Homage to the Buddha of Boundless Light!',
        'meta_description' => 'Offer before Amitābha at an online Buddhist altar. Light lamps, offer incense, water, flowers, and music while reciting the prayer to the Buddha of Boundless Light.',
        'page_title' => 'Amitābha Shrine — Buddhist Altar',
        'seo_title' => 'Amitābha Online Shrine — Buddhist Altar',
        'deity_image' => 'images/amitabha.webp',
        'deity_image_class' => 'deity-image deity-image--amitabha',
        'deity_alt' => 'Amitābha, the Buddha of Boundless Light',
        'body_class' => 'shrine-bg',
        'show_sky_clouds' => true,
        'prayer_partial' => 'partials.amitabha-prayer',
        'prayer_modal_title' => 'Prayer to Buddha Amitābha',
        'read_prayer_label' => 'Read the Prayer',
    ],
];
